### ISSUE TITLE
Line friend limit

### ISSUE THREAD

**Issue by DF-wu** [penut85420/FriesMeowLinebot#1]
I can't join it because line friend limit.

**Comment by penut85420** [comment]
Sorry about that, I didn't notice that I've use develope trial account that has 50 friends limiit.
I'm testing with normal free account, if there's no problem, I'll swap to it, thank you!

**Comment by DF-wu** [comment]
Thank you for your replying.

Actually, we can talk with Chinese because I am NTOU student XDD.

I noticed it on PTT/NTOU_CS.


It's a funny program after  trying it on my friend's device.


Sincerely,
a2470abc

**Comment by penut85420** [comment]
我想也是哈哈哈哈
我開了一個群組
在群組裡面就可以不用加好友也能跟薯條互動～
https://line.me/R/ti/g/erpyZX0yk3
